conf/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("toppage.urls")),
    path("accounts/",include("accounts.urls")),
    path("mypage/",include("mypage.urls")),
    path("movie/",include("movie.urls")),
    path("usersearch/",include("usersearch.urls")),
    path("consider/",include("consider.urls")),
    path("ranking/",include("ranking.urls")),
    path("comment/", include("comment.urls")),
    path("mail/", include("mail.urls")),
    path("topic/", include("topic.urls")),
    path('', include('social_django.urls', namespace='social')),
]

movie/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MovieSearchView,MovieDetailView,AddMyList
from django.contrib.auth.decorators import login_required
app_name = "movie"
urlpatterns = [
      path('search', MovieSearchView.as_view(),name = "movie_search"),
      path('search/result/<str:movie_name>', MovieDetailView.as_view(),name = "movie_detail"), 
      path("search/add/<str:name>",login_required(AddMyList),name = "add_mylist"), #mylistに追加するときはログイン必須  
]

mypage/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MylistView,DeleteView
from django.urls import path
from . import views

app_name = 'mypage'
urlpatterns = [
    
    path('mylist/', MylistView.as_view(),name = "mylist"),
    path('delete/<int:pk>', DeleteView.as_view(), name='delete'),
    

]

topic/urls.py
from django.contrib import admin
from django.urls import path,include
from.views import TopicTop
app_name = "topic"
urlpatterns = [
    path('top', TopicTop.as_view(),name = "top"),
]

toppage/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import TopPageView,OpeningView
app_name = "toppage"
urlpatterns = [
    path('', OpeningView.as_view(),name = "opening"),
    path('toppage', TopPageView.as_view(),name = "toppage"),
    
]

usersearch/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UserSearchView,UserMoviesView
from django.urls import path
from . import views

app_name = 'usersearch'
urlpatterns = [
    
    path('search/', UserSearchView.as_view(),name = "user_search"),
    path("user/<int:pk>/movies/",UserMoviesView.as_view(),name ="other_user_movie")

]

toppage/models.py
from django.db import models

# Create your models here.
class ThisWeekMovies(models.Model):
    title = models.CharField("映画名",max_length=50)
    day = models.DateField("公開日")
    youtube = models.TextField("youtubeの動画id(例 https://www.youtube.com/watch?v=pjXW-hDfUzc の pjXW-hDfUzcの部分)",max_length=10000)
    overview = models.TextField("映画概要",max_length=10000)
 
    def __str__(self):
          return self.title

toppage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import ThisWeekMovies
from datetime import datetime, timedelta

class OpeningView(TemplateView):
    template_name = "toppage/opening.html"

class TopPageView(TemplateView):
    template_name = "toppage/toppage.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = super().get_context_data(**kwargs)

        # 今日の日付を取得
        today = datetime.today().date()

        # 1週間後の日付を計算
        one_week_later = today + timedelta(days=7)

        # 今日から1週間後までのイベントを取得
        movies = ThisWeekMovies.objects.filter(day__range=[today, one_week_later])
        context['movies'] = movies.all().order_by('day')
        return context
        

templates/toppage/opening.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Opening </title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="opening-animation">
  <div class="image-container">
    <img src="{% static 'img_folder/logo.jpg' %}" alt="Opening Image">
  </div>
  <h1 class="title">-映画の感動をずっと手元に-</h1>
</div>
<style>
    body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
  background-color: #000000;
}

.opening-animation {
  position: relative;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.image-container {
  width: 100%;
  max-width: 250px; /* 画像の最大幅を設定 */
  opacity: 0;
  animation: fadeInImage 2s ease forwards;
}

.image-container img {
  width: 100%;
  height: auto;
  display: block;
  border-radius: 10px; /* 画像に丸みを持たせる場合 */
}

.title {
  font-size: 20px;
  color: #ffffff;
  margin-top: 20px;
  opacity: 0;
  animation: fadeInTitle 2s 1s forwards; /* タイトルの表示を遅延させる */
}

@keyframes fadeInImage {
  0% {
    opacity: 0;
    transform: translateY(-20px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes fadeInTitle {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
<script>
    document.addEventListener('DOMContentLoaded', function() {
  
  const animationDuration = 3000; 
  const delayBeforeRedirect = 1000; 

  setTimeout(function() {
    window.location.href = '{% url "toppage:toppage" %}';
  }, animationDuration + delayBeforeRedirect);
});
</script>
</body>
</html>

templates/toppage/toppage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}トップページ{% endblock %}
{% block content %}

<!-- スライドの外枠 -->
<div class="slide-wrapper" id="big-slide">
    <!-- スライド（コンテンツ） -->
    <div id="slide" class="slide">
      <div>
        <a href='{% url "movie:movie_search" %}'><img src="{% static 'img_folder/search.png' %}"  style = "max-width:87%;" alt="検索画面"></a>
      </div>
      <div>
        <a href='{% url "mypage:mylist" %}'><img src="{% static 'img_folder/mylist.png' %}" style = "max-width:89%;" alt="マイリスト画面"></a>
      </div>
      <div>
        <a href='{% url "usersearch:user_search" %}'><img src="{% static 'img_folder/account.png' %}"  style = "max-width:89%;" alt="アカウント検索画面"></a>
      </div>
      <div><!--写真のurlは後でおすすめ検索機能用の写真に変える-->
        <a href='{% url "topic:top" %}'><img src="{% static 'img_folder/topic_img.png' %}" style = "max-width:87%;" alt="特集映画"></a>
      </div>
    </div>
    <!-- 左右のボタン   リストが動くようにするため -->
    <div id="prev" class="prev"></div>
    <div id="next" class="next"></div>
    <!-- インジケーター -->
    <ul class="indicator" id="indicator">
      <li class="list"></li>
      <li class="list"></li>
      <li class="list"></li>
      <li class="list"></li>
    </ul>
  </div>

   <!-- スライドショーjs -->
    <script>
    const slide = document.getElementById('slide');
    const prev = document.getElementById('prev');
    const next = document.getElementById('next');
    const indicator = document.getElementById('indicator');
    const lists = document.querySelectorAll('.list');
    const totalSlides = lists.length;
    let count = 0;
    let autoPlayInterval;
    function updateListBackground() {
        for (let i = 0; i < lists.length; i++) {
            lists[i].style.backgroundColor = i === count % totalSlides ? '#000' : '#fff';
        }
    }
    function nextClick() {
        slide.classList.remove(`slide${count % totalSlides + 1}`);
        count++;
        slide.classList.add(`slide${count % totalSlides + 1}`);
        updateListBackground();
    }
    function prevClick() {
         slide.classList.remove(`slide${count % totalSlides + 1}`);
         count--;
         if (count < 0) count = totalSlides - 1;
         slide.classList.add(`slide${count % totalSlides + 1}`);
         updateListBackground();
    }
    function startAutoPlay() {
        autoPlayInterval = setInterval(nextClick, 3000);
    }
    function resetAutoPlayInterval() {
        clearInterval(autoPlayInterval);
        startAutoPlay();
    }
    next.addEventListener('click', () => {
    nextClick();
    resetAutoPlayInterval();
    });
    prev.addEventListener('click', () => {
    prevClick();
    resetAutoPlayInterval();
    });
    indicator.addEventListener('click', (event) => {
    if (event.target.classList.contains('list')) {
        const index = Array.from(lists).indexOf(event.target);
        slide.classList.remove(`slide${count % totalSlides + 1}`);
        count = index;
        slide.classList.add(`slide${count % totalSlides + 1}`);
        updateListBackground();
        resetAutoPlayInterval();
    }
    });
    startAutoPlay();
    </script>
<style>

.slide-wrapper{
  margin:0px;
  padding:0px;
  background-size: cover;
  background-position: center top;
  background-repeat: no-repeat;
}

#big-slide {
  background-image:url("/static/img_folder/file2.jpg");
  min-height: 100vh;
}
/* ↓ スライドショー*/
ul {
 margin: 0;
 padding: 0;
}

li {
list-style: none;
}
/* ↓ スライドの外枠 */
.slide-wrapper {
width: 100%;
height: 700px;
top: 120px;

}
/*  ↓ スライド（コンテンツ） */
.slide { /*スライド全体 */
width: 400%;
height: 76%;
display: flex;
transition: all 0.3s;
}
.slide div { /* スライド */
width: 25%;
height: 100%;
display: flex;
text-align: center;
justify-content: center;
align-items: center;
}
.slide1 { /* スライドさせるために必要なクラス */
transform: translateX(0);
}
.slide2 { /* スライドさせるために必要なクラス */
transform: translateX(-25%);
}
.slide3 { /* スライドさせるために必要なクラス */
transform: translateX(-50%);
}
.slide4 { /* スライドさせるために必要なクラス */
transform: translateX(-75%);
}

/* ↓ 左右のボタン */
.next {
width: 0px;
height: 0px;
right: 4px;
bottom: 80%;
z-index: 10;
cursor: pointer;
border-top: solid 3px #000;
border-right: solid 3px #000;
-webkit-transform: rotate(45deg) translateY(50%);
transform: rotate(45deg) translateY(50%);
}

.prev {
width: 0px;
height: 0px;
left: 40px;
bottom: 80%;
z-index: 10;
cursor: pointer;
border-top: solid 3px #000;
border-right: solid 3px #000;

}
/* ↓ インジケーター */
.indicator {
width: 100%;
display: flex;
column-gap: 18px;
justify-content: center;
align-items: center;
}

.indicator li {
width: 14px;
height: 14px;
border-radius: 35%;
list-style: none;
background-color: #fff;
border: 2px #000 solid;
cursor: pointer;
}
.indicator li:first-of-type {
background-color: #000;
}
</style>

<!--ここから今週の映画の内容-->
<h1 class="title" >１週間以内に公開の映画</h1>
<div class="movie_section">
  
{% for movie in movies%}


<div class="article">
  <h2>{{movie.title}}({{ movie.day|date:"Md日" }}公開)</h2>
  <div style="position: relative; padding-bottom: 56.25%;">
    <iframe 
      style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
      src="https://www.youtube.com/embed/{{movie.youtube}}"
      frameborder="0" 
      allow="autoplay; 
      encrypted-media" 
      allowfullscreen>
    </iframe>
  </div>
  <p>{{movie.overview}}</p>
</div>
{% endfor%}
</div>
<style>
  .youtube{
    width: 50%;
    height: auto;
  }
  .title{
    padding-top: 50px;
    color: #0d0d0d;
    padding-left:20px;
  }
   .movie_sevtion{
   
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            padding-left:50px;
            
        }
        .article {
          width: 80%;
            padding-left: 50px;
            padding-right: 50px;
        
            border-bottom: 1px solid #ccc;
            padding-bottom: 20px;
            text-align: left; /* 各記事のコンテンツを左揃え */
            background-color: white;
            Border-radius:10px;
            margin-right: 10px;
        }
        .article h2 {
          padding-top: 10px;
            font-size: 24px;
            margin-bottom: 10px;
            
        }
        
        .article p {
          width:80%;
            font-size: 16px;
            line-height: 1.8;
            background-color: #fff;
        }
 </style>
{% endblock %}