comment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import CommentView, like_comment, CommentDeleteView
app_name = "comment"
urlpatterns = [
      path("",CommentView.as_view(), name="comment"),
      path('like/<int:comment_id>/', login_required(like_comment), name='like_comment'),
      path('delete/<int:pk>/', CommentDeleteView.as_view(), name='delete'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("toppage.urls")),
    path("accounts/",include("accounts.urls")),
    path("mypage/",include("mypage.urls")),
    path("movie/",include("movie.urls")),
    path("usersearch/",include("usersearch.urls")),
    path("consider/",include("consider.urls")),
    path("ranking/",include("ranking.urls")),
    path("comment/", include("comment.urls")),
    path("mail/", include("mail.urls")),
    path("topic/", include("topic.urls")),
    path('', include('social_django.urls', namespace='social')),
]

movie/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MovieSearchView,MovieDetailView,AddMyList
from django.contrib.auth.decorators import login_required
app_name = "movie"
urlpatterns = [
      path('search', MovieSearchView.as_view(),name = "movie_search"),
      path('search/result/<str:movie_name>', MovieDetailView.as_view(),name = "movie_detail"), 
      path("search/add/<str:name>",login_required(AddMyList),name = "add_mylist"), #mylistに追加するときはログイン必須  
]

comment/models.py
from django.db import models
from accounts.models import CustomUser
from movie.models import MyMovieModel
from datetime import datetime

SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class Comment(models.Model):
    # movie_nameとimagepathのリレーションに関しては自信なし。Foreignkeyかも
    movie_name = models.ForeignKey(MyMovieModel, verbose_name="映画名", related_name='movie_comments', on_delete=models.CASCADE)
    # overview = models.CharField("映画の概要", max_length=10000)
    imagepath = models.CharField(verbose_name="映画の画像", max_length = 1000)
    user = models.ForeignKey(CustomUser,verbose_name="追加したユーザー", on_delete=models.CASCADE)
    comment = models.CharField(verbose_name="コメント", max_length = 1000)
    rating = models.IntegerField(choices=SCORE_CHOICES)
    date = models.DateTimeField(auto_now_add=True, verbose_name="投稿日")
    likes = models.IntegerField(default=0)

    def __str__(self):
       return f'{self.movie_name.name} - {self.user.username}'
    

class Like(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_likes')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_comment')

    class Meta:
        unique_together = ('user', 'comment')

comment/forms.py
# forms.py
from django import forms
from .models import Comment
from movie.models import MyMovieModel

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['movie_name', 'comment', 'rating']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['movie_name'].queryset = MyMovieModel.objects.filter(createUser=user)

# class MovieFilterForm(forms.Form):
#     movie_name = forms.ModelChoiceField(
#         queryset=MyMovieModel.objects.filter(movie_comments__isnull=False).distinct("name"),
#         required=False,
#         label='Filter by Movie'
#     )

class MovieFilterForm(forms.Form):
    movie_name = forms.ChoiceField(
        choices=[('', '---------')] + [(movie['name'], movie['name']) for movie in MyMovieModel.objects.filter(movie_comments__isnull=False).values('name').distinct()],
        required=False,
        label='Filter by Movie'
    )

comment/views.py
# views.py
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, DeleteView
from .models import Comment, Like
from movie.models import MyMovieModel
from .forms import CommentForm, MovieFilterForm
from django.contrib.auth.mixins import LoginRequiredMixin

class CommentView(LoginRequiredMixin,View):
    def get(self, request):
        comment_form = CommentForm(user=request.user)
        filter_form = MovieFilterForm(request.GET or None)
        comments = Comment.objects.all().order_by('-date')

        if filter_form.is_valid() and filter_form.cleaned_data['movie_name']:
            comments = comments.filter(movie_name=filter_form.cleaned_data['movie_name'])

        return render(request, 'comment/comment.html', {
            'comment_form': comment_form,
            'filter_form': filter_form,
            'comments': comments
        })

    def post(self, request):
        comment_form = CommentForm(request.POST, user=request.user)
        filter_form = MovieFilterForm(request.GET or None)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            movie = comment_form.cleaned_data['movie_name']
            comment.imagepath = movie.imagepath
            comment.save()
            return redirect('/comment')

        comments = Comment.objects.all().order_by('-date')
        if filter_form.is_valid() and filter_form.cleaned_data['movie_name']:
            comments = comments.filter(movie_name=filter_form.cleaned_data['movie_name'])

        return render(request, 'comment/comment.html', {
            'comment_form': comment_form,
            'filter_form': filter_form,
            'comments': comments
        })

class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'comment/delete.html'
    success_url = reverse_lazy('comment:comment')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        # ログインユーザーのオブジェクトのみを返す
        return queryset.filter(user=self.request.user, id=self.kwargs['pk'])

    def get_object(self, queryset=None):
        # 削除するオブジェクトを取得する
        obj = super().get_object(queryset)
        if obj is None:
            # オブジェクトが存在しない場合は404エラーを返す
            raise Http404("オブジェクトが見つかりません")
        return obj
    
def like_comment(request, comment_id):
    if request.method == "POST":
        comment = get_object_or_404(Comment, id=comment_id)

        user = request.user

        # 既に「いいね」しているか確認
        existing_like = Like.objects.filter(user=user, comment=comment)
        if existing_like:
            # 「いいね」を取り消す
            existing_like.delete()
            comment.likes -= 1
            comment.save()
            return JsonResponse({'likes': comment.likes, 'message': 'Like removed'})
        else:
            # 「いいね」を追加
            Like.objects.create(user=user, comment=comment)
            comment.likes += 1
            comment.save()
            return JsonResponse({'likes': comment.likes, 'message': 'Like added'})


    return JsonResponse({'error': 'Invalid request'}, status=400)

templates/comment/comment.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'comment.css' %}">

    <div class="comment">
      <h1>Comments</h1>
      <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button class="head" type="submit">送信</button>
      </form>
      <hr>
    </div>

    <div class="filter">
      <h2>Filter</h2>
      <form method="get">
        {{ filter_form.as_p }}
        <button class="head" type="submit">絞り込み検索</button>
      </form>
      <hr>
    </div>
    <main>
      <div class="list">
        <h1>ーコメント覧ー</h1>
      </div>
        <ul class="comment-list">
        {% for comment in comments %}
        <li class="comment-list-content">
          <div class="img">
            <img src="{{ comment.imagepath }}" alt="">
          </div>
          <div class="comment-info">
            <h3><a href="{% url 'movie:movie_detail' comment.movie_name %}">{{ comment.movie_name }}</a></h3>
            <p>ユーザー名：{{ comment.user }}</p>
            <p>日時：{{ comment.date |date:"Md日"}}</p>
            <p>評価：{{ comment.get_rating_display }}</p>
            <p>{{ comment.comment }}</p>
            <button class="like-btn" data-id="{{ comment.id }}">Like</button>
            <p><span class="like-cnt" id="likes-{{ comment.id }}">{{ comment.likes }}</span> likes</p>
            <div class="error-message" id="error-{{ comment.id }}"></div>
            {% if comment.user == user %}
            </a>
              <button type="submit" class="btn"><a href = "{% url 'comment:delete' comment.id %}">Delete</a></button>
            </a>
            {% endif %}
          </div>
        </li>
        {% endfor %}
      </ul>
    </main>


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function(){
      $('.like-btn').click(function(){
        var commentId = $(this).data('id');
        var url = "{% url 'comment:like_comment' comment_id=0 %}".replace('0', commentId);
        console.log(url);  // 生成されたURLをコンソールに出力して確認する
        $.ajax({
          url: url,
          method: 'POST',
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}'
          },
          success: function(response) {
            $('#likes-' + commentId).text(response.likes);
          },
          error: function(xhr, status, error) {
            $('#error-' + commentId).text(JSON.parse(xhr.responseText).error);
          }
        });
      });
    });
  </script>
{% endblock %}


<!--
<section class="get-in-touch">
   <h1 class="title">Get in touch</h1>
   <form class="contact-form row">
      <div class="form-field col x-50">
         <input id="name" class="input-text js-input" type="text" required>
         <label class="label" for="name">Name</label>
      </div>
      <div class="form-field col x-50">
         <input id="email" class="input-text js-input" type="email" required>
         <label class="label" for="email">E-mail</label>
      </div>
      <div class="form-field col x-100">
         <input id="message" class="input-text js-input" type="text" required>
         <label class="label" for="message">Message</label>
      </div>
      <div class="form-field col x-100 align-center">
         <input class="submit-btn" type="submit" value="Submit">
      </div>
   </form>
</section>
<p class="note">Based on <a class="link" href="http://redcollar.digital/contacts/" target="blank">Red Collar Contact Form</a>.</p>
-->

templates/comment/comments.html
<!-- comments.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Comments</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post Comment</button>
  </form>

  <h2>All Comments</h2>
  <ul>
    {% for comment in comments %}
      <li>
        <strong><a href="{% url 'movie:movie_detail' comment.movie_name %}">{{ comment.movie_name }}</a></strong>
        {{ comment.imagepath }}<br>
        by {{ comment.user }} on {{ comment.date }}<br>
        Rating: {{ comment.rating }}<br>
        {{ comment.comment }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/comment/delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'delete.css' %}">
    <main>
        <div>
            <h2>本当に削除しますか？</h2>
            <form method="POST" >
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        </div>
        <a href={% url "comment:comment" %}><button class="mylist-btn">コメントに戻る</button></a>
    </main>
{% endblock %}