conf/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("toppage.urls")),
    path("accounts/",include("accounts.urls")),
    path("mypage/",include("mypage.urls")),
    path("movie/",include("movie.urls")),
    path("usersearch/",include("usersearch.urls")),
    path("consider/",include("consider.urls")),
    path("ranking/",include("ranking.urls")),
    path("comment/", include("comment.urls")),
    path("mail/", include("mail.urls")),
    path("topic/", include("topic.urls")),
    path('', include('social_django.urls', namespace='social')),
]

movie/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MovieSearchView,MovieDetailView,AddMyList
from django.contrib.auth.decorators import login_required
app_name = "movie"
urlpatterns = [
      path('search', MovieSearchView.as_view(),name = "movie_search"),
      path('search/result/<str:movie_name>', MovieDetailView.as_view(),name = "movie_detail"), 
      path("search/add/<str:name>",login_required(AddMyList),name = "add_mylist"), #mylistに追加するときはログイン必須  
]

mypage/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MylistView,DeleteView
from django.urls import path
from . import views

app_name = 'mypage'
urlpatterns = [
    
    path('mylist/', MylistView.as_view(),name = "mylist"),
    path('delete/<int:pk>', DeleteView.as_view(), name='delete'),
    

]

usersearch/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UserSearchView,UserMoviesView
from django.urls import path
from . import views

app_name = 'usersearch'
urlpatterns = [
    
    path('search/', UserSearchView.as_view(),name = "user_search"),
    path("user/<int:pk>/movies/",UserMoviesView.as_view(),name ="other_user_movie")

]

mypage/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, DeleteView
from movie.models import MyMovieModel
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.http import Http404
    
    
class MylistView(LoginRequiredMixin, TemplateView):
    template_name = 'mypage/mylist.html'

    def get(self, request):

        MyMovieModel_data = MyMovieModel.objects.filter(createUser=self.request.user)
        context = {
            'MyMovieModel_data': MyMovieModel_data
        }
        return render(request, 'mypage/mylist.html', context)
    
    
class DeleteView(LoginRequiredMixin, DeleteView):
    model = MyMovieModel
    template_name = 'mypage/delete.html'
    success_url = reverse_lazy('mypage:mylist')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        # ログインユーザーのオブジェクトのみを返す
        return queryset.filter(createUser=self.request.user, id=self.kwargs['pk'])

    def get_object(self, queryset=None):
        # 削除するオブジェクトを取得する
        obj = super().get_object(queryset)
        if obj is None:
            # オブジェクトが存在しない場合は404エラーを返す
            raise Http404("オブジェクトが見つかりません")
        return obj

templates/mypage/delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'delete.css' %}">
    <main>
        <div>
            <h2>本当に削除しますか？</h2>
            <form method="POST" >
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        </div>
        <a href={% url "mypage:mylist" %}><button class="mylist-btn">マイリストに戻る</button></a>
    </main>
{% endblock %}

templates/mypage/mylist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'mylist.css' %}">
    <main>
        <div style="display: flex; align-items: center;">
            <a href="https://twitter.com/share?url={% url 'usersearch:other_user_movie' request.user.id %}" class="twitter-share-button"  data-lang="ja" data-show-count="false"></a>
            <div class="line-it-button" data-lang="ja" data-type="share-a" data-env="REAL" data-url="{% url 'usersearch:other_user_movie' request.user.id %}" data-color="default" data-size="small" data-count="false" data-ver="3" style="display: none;"></div>
            <div class="fb-share-button" data-href="{% url 'usersearch:other_user_movie' request.user.id %}" data-layout="button_count"></div>
        </div>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v10.0" nonce="D3w4c3G0"></script>

        <ul class="book-list">
        {% for data in MyMovieModel_data %}
        <li class="book">
            <a href={% url "movie:movie_detail" data.name %}>
                <img src="{{ data.imagepath }}" alt="映画の画像">
                <div class="book-info">
                <p>{{ data.name }}</p>
                </div>
            </a>
                <button type="submit" class="btn"><a href = "{% url 'mypage:delete' data.pk %}">削除</a></button>
            </a>
        </li>
     
       

        {% endfor %}
    </ul>

    </main>

    {% endblock %}