comment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import CommentView, like_comment, CommentDeleteView
app_name = "comment"
urlpatterns = [
      path("",CommentView.as_view(), name="comment"),
      path('like/<int:comment_id>/', login_required(like_comment), name='like_comment'),
      path('delete/<int:pk>/', CommentDeleteView.as_view(), name='delete'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("toppage.urls")),
    path("accounts/",include("accounts.urls")),
    path("mypage/",include("mypage.urls")),
    path("movie/",include("movie.urls")),
    path("usersearch/",include("usersearch.urls")),
    path("consider/",include("consider.urls")),
    path("ranking/",include("ranking.urls")),
    path("comment/", include("comment.urls")),
    path("mail/", include("mail.urls")),
    path("topic/", include("topic.urls")),
    path('', include('social_django.urls', namespace='social')),
]

mail/urls.py
from django.urls import path
from .views import Mail_list, Mail_detail, Unread_list

app_name = 'mail'
urlpatterns = [
    path('', Mail_list.as_view(), name='mail_list'),
    path('unread/', Unread_list.as_view(), name='unread_mail_list'),
    path('detail/<int:pk>', Mail_detail.as_view(), name='mail_detail'),
]

movie/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MovieSearchView,MovieDetailView,AddMyList
from django.contrib.auth.decorators import login_required
app_name = "movie"
urlpatterns = [
      path('search', MovieSearchView.as_view(),name = "movie_search"),
      path('search/result/<str:movie_name>', MovieDetailView.as_view(),name = "movie_detail"), 
      path("search/add/<str:name>",login_required(AddMyList),name = "add_mylist"), #mylistに追加するときはログイン必須  
]

mypage/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import MylistView,DeleteView
from django.urls import path
from . import views

app_name = 'mypage'
urlpatterns = [
    
    path('mylist/', MylistView.as_view(),name = "mylist"),
    path('delete/<int:pk>', DeleteView.as_view(), name='delete'),
    

]

usersearch/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UserSearchView,UserMoviesView
from django.urls import path
from . import views

app_name = 'usersearch'
urlpatterns = [
    
    path('search/', UserSearchView.as_view(),name = "user_search"),
    path("user/<int:pk>/movies/",UserMoviesView.as_view(),name ="other_user_movie")

]

usersearch/models.py
from django.db import models

usersearch/forms.py
from django import forms

class UserSearchForm(forms.Form):
    username = forms.CharField(label='ユーザー名')
    #results1 = forms.CharField(label="検索結果")



from accounts.models import CustomUser
class CustomUserForm(forms.ModelForm):
      class Meta:
          model = CustomUser
          fields = ('username',)

usersearch/views.py
from django.views.generic import FormView, DetailView, ListView
from accounts.models import CustomUser
from movie.models import MyMovieModel
from .forms import UserSearchForm

class UserSearchView(FormView):
    template_name = 'usersearch/userlist.html'
    form_class = UserSearchForm
    context_object_name = 'users'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        users = CustomUser.objects.filter(username__icontains=username)
        return self.render_to_response(self.get_context_data(users=users))
    

class UserMoviesView(DetailView):
    model = CustomUser
    template_name = 'usersearch/userlist_result.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = MyMovieModel.objects.filter(createUser=self.object)
        return context

templates/usersearch/userlist.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'userlist.css' %}">
<div class="user">
  <h2>ユーザー検索</h2>
  <form method="post">
    {% csrf_token %}
    <p>{{ form.as_p }}</p>
    <button type="submit">検索</button>
  </form>

  {% if users %}
    <h2>ー検索結果ー</h2>
    <div class="but">
      {% for user in users %}
        <div class="but2"><a href="{% url 'usersearch:other_user_movie' user.id %}">{{ user.username }}</a></div>
      {% endfor %}</div>
  {% endif %}
</div>
{% endblock %}

templates/usersearch/userlist_result.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img_folder/logo.ico' %}">
    <link rel="stylesheet" href="{% static 'mylist.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header class="c-header c-hamburger-menu">
       <a href='{% url "toppage:toppage" %}'><img class="logoimg" src="{% static 'img_folder/logo.jpg' %}" alt="トップページへ"></a>
        <input type="checkbox" name="hamburger" id="hamburger" class="c-hamburger-menu__input"/><!-- 追記 idはlabelのforと同じにする -->
        <label for="hamburger" class="c-hamburger-menu__bg"></label><!-- 追記 ハンバーガーメニュを開いた時の背景 -->
        <ul class="c-header__list c-hamburger-menu__list">
            {% if user.is_authenticated %}
            <li><span>{{ user.get_username }}</span><span>の映画リストを閲覧中です</span></li>
            {% endif %}
            <li class="c-header__list-item"><a href='{% url "ranking:ranking" %}' class="c-header__list-link">ランキング</a></li>
            <li class="c-header__list-item"><a href='{% url "comment:comment" %}' class="c-header__list-link">コメント</a></li>
            <li class="c-header__list-item"><a href='{% url "movie:movie_search" %}' class="c-header__list-link">映画検索</a></li>
            <li class="c-header__list-item"><a href='{% url "mypage:mylist" %}' class="c-header__list-link">マイリスト</a></li>
            <li class="c-header__list-item"><a href='{% url "usersearch:user_search" %}' class="c-header__list-link">アカウント検索</a></li>
            <li class="c-header__list-item"><a href='{% url "consider:top" %}' class="c-header__list-link">映画診断</a></li>
            <li class="c-header__list-item"><a href='{% url "mail:mail_list" %}' class="c-header__list-link">お知らせ</a></li>
            {% if user.is_authenticated %}
            <li class="c-header__list-item">
              <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout">ログアウト</button>
              </form>
            </li>
            {% else %}
            <li class="c-header__list-item"><a href='{% url "accounts:login" %}' class="c-header__list-link">ログイン</a></li>
            <li class="c-header__list-item"><a href='{% url "accounts:custom_accounts_create" %}' class="c-header__list-link">アカウント登録</a></li>
            {% endif %}
        </ul>
        <label for="hamburger" class="c-hamburger-menu__button"><!-- 追記 ハンバーガーメニューのボタン -->
            <span class="c-hamburger-menu__button-mark"></span>
            <span class="c-hamburger-menu__button-mark"></span>
            <span class="c-hamburger-menu__button-mark"></span>
        </label>
        </div>
    </header>
<style>
html,body {
  overflow-x: hidden;
  margin: 0;
  padding: 0;
}
        
header{
  z-index: 1000;
}

.c-header {
  align-items: center;
  font-weight: bold;
  background-color: #000000; 
  box-sizing: border-box;
  display: flex;
  justify-content: space-between;
  padding: 1rem 2rem; 
  width: 100%;
}

.logout {
  background-color:#ffff00; /* ボタンの背景色 */
  font-weight: bold;
  border: none;
  color: black; /* ボタンのテキスト色 */
  padding: 10px 13px; /* ボタンのパディング */
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 15px;
  margin: 0px 2px 0px 0px;
  cursor: pointer;
  border-radius: 4px; /* ボタンの角丸 */
  transition-duration: 0.4s;
}

/* ボタンのホバースタイル */
.logout:hover {
    background-color: #e6e6e6; /* ホバー時の背景色 */
}

#color {
  color: #ffffff;
  display: block;
  font-size: 18px;
  margin-right: 20px; 
  padding: 7px 0px;
}

.logoimg{
    height: 70px;
    width: auto;
}
.c-header__logo {
  color: #000; /* カスタマイズしてください */
  min-width: 80px; /* カスタマイズしてください */
  text-decoration: none;
}

.c-header__list {
  box-sizing: border-box;
  display: flex;
  margin: 0;
  padding: 0;
  
}
.c-header__list-item {
  list-style: none;
  text-decoration: none;
}

.c-header__list-link {
  color: #ffffff; /* カスタマイズしてください */
  display: block;
  margin-right: 20px; /* カスタマイズしてください */
  text-decoration: none;
  padding: 10px 0px; /* カスタマイズしてください */
}

.c-header__list-link:hover {
  filter: opacity(0.6); /* カスタマイズしてください */
}

.c-hamburger-menu {
  position: relative;
}

@media screen and (max-width: 750px) {
  .c-hamburger-menu__list {
    background-color: #000000; /* カスタマイズしてください */
    align-items: flex-start;
    display: flex;
    flex-direction: column;
    left: 0;
    padding: 2rem; /* カスタマイズしてください */
    position: absolute;
    transform: translateX(-100%);
    transition: 0.3s; /* カスタマイズしてください */
    top: 100%;
    width: 100%;
  }

  #hamburger:checked ~ .c-hamburger-menu__list {
    transform: translateX(0%);
    transition: 0.3s;
  }
}

.c-hamburger-menu__input {
  display: none;
}

.c-hamburger-menu__bg {
  background-color: #000; /* カスタマイズしてください */
  cursor: pointer;
  display: none;
  height: 100vh;
  left: 0;
  opacity: 0.4; /* カスタマイズしてください */
  position: absolute;
  top: 0;
  width: 100%;
  z-index: -1;
}

#hamburger:checked ~ .c-hamburger-menu__bg {
  display: block;
}

.c-hamburger-menu__button {
  display: none;
}

@media screen and (max-width: 750px) {
  .c-hamburger-menu__button {
    align-items: center;
    appearance: none;
    background-color: transparent;
    border: none;
    cursor: pointer;
    display: flex;
    flex-direction: column;
    gap: 5px; /* カスタマイズしてください */
    height: 32px; /* カスタマイズしてください */
    justify-content: center;
    width: 32px; /* カスタマイズしてください */
    
  }
}

.c-hamburger-menu__button-mark {
  background-color:white; /* カスタマイズしてください */
  display: block;
  height: 1px; /* カスタマイズしてください */
  transition: 0.3s; /* カスタマイズしてください */
  width: 20px; /* カスタマイズしてください */
}

@media screen and (max-width: 750px) {
  #hamburger:checked
    ~ .c-hamburger-menu__button
    .c-hamburger-menu__button-mark:nth-of-type(1) {
    transform: translate(2px, 1px) rotate(45deg); /* カスタマイズしてください */
    transform-origin: 0%; /* カスタマイズしてください */
  }
  #hamburger:checked
    ~ .c-hamburger-menu__button
    .c-hamburger-menu__button-mark:nth-of-type(2) {
    opacity: 0;
  }
  #hamburger:checked
    ~ .c-hamburger-menu__button
    .c-hamburger-menu__button-mark:nth-of-type(3) {
    transform: translate(2px, 3px) rotate(-45deg); /* カスタマイズしてください */
    transform-origin: 0%; /* カスタマイズしてください */

  }
}
</style>
    </header>

    {% block content %}
    <main>
        <h1>{{ user.username }}'s Movies List</h1>
        <ul class="book-list">
        {% for movie in movies %}
        <div class="book">
            <a href="{% url 'movie:movie_detail' movie.name %}">
                <img src="{{ movie.imagepath }}" alt="">
                <p>{{ movie.name }}</p>
            </a>
        </div>
        {% endfor %}
        </ul>
    </main>    
    {% endblock %}
    
</body>
</html>

<!--
<body>
  <header class="header">
    <div class="navtext-container">
      <div class="navtext">company</div>
    </div>
    <input type="checkbox" class="menu-btn" id="menu-btn">
    <label for="menu-btn" class="menu-icon"><span class="navicon"></span></label>
    <ul class="menu">
      <li class="top"><a href="#home">home</a></li>
      <li><a href="#skills">skills</a></li>
      <li><a href="#projects">projects</a></li>
      <li><a href="#contact">contact</a></li>
    </ul>

  </header>

</body>

</html>
-->